name: Build JXL

on:
  workflow_dispatch:

jobs:
  build-macos:
    name: macOS Build
    runs-on: macos-latest

    env:
      BASE_DIR: ${{ github.workspace }}/im_build 
      WORKING_DIR: ${{ github.workspace }}

    steps:
    - name: Install dependencies
      run: |
        set -e
        
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew install pkg-config nasm yasm gettext autoconf automake python@3.9 coreutils ninja

    - name: Build Deps
      run: |
        export CURR_DIR=$(PWD)
        export DELEGATES=$CURR_DIR/im_build
              
        export CC="clang -mmacosx-version-min=10.15"
        export CXX="clang++ -std=c++17 -stdlib=libc++ -mmacosx-version-min=10.15"
        export OBJC="clang -mmacosx-version-min=10.15"
        export OBJCXX="clang++ -std=c++17 -stdlib=libc++ -mmacosx-version-min=10.15"
        export AS="as -mmacosx-version-min=10.15"
        export LD="ld -macosx_version_min 10.15"
              
        mkdir -p $DELEGATES

        echo "+--------------------------------"
        echo "| Building jxl"
        echo "+--------------------------------"
    
        git clone --branch v0.8.0 https://github.com/libjxl/libjxl.git --recursive --shallow-submodules
        cd libjxl
        mkdir buildir && cd buildir
    
        cmake .. -DCMAKE_BUILD_TYPE=Release \
                  -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
                  -DCMAKE_INSTALL_PREFIX=blabla \
                  -DBUILD_TESTING=NO \
                  -DAVIF_FOUND=NO \
                  -DWebP_FOUND=NO \
                  -DJPEGXL_ENABLE_DOXYGEN=NO \
                  -DJPEGXL_ENABLE_JNI=NO \
                  -DJPEGXL_ENABLE_OPENEXR=YES \
                  -DJPEGXL_ENABLE_SJPEG=NO \
                  -DJPEGXL_ENABLE_SKCMS=YES \
                  -DJPEGXL_FORCE_SYSTEM_BROTLI=NO \
                  -DJPEGXL_FORCE_SYSTEM_HWY=NO
    
        cmake --build . -- -j$(nproc)

        
