name: macOS Test

on:
  workflow_dispatch:

jobs:
  build-macos:
    name: macOS Build
    runs-on: macos-12

    env:
      BASE_DIR: ${{ github.workspace }}/im_build 
      WORKING_DIR: ${{ github.workspace }}

    steps:
    - name: Install dependencies
      run: |
        set -e
        
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew install pkg-config nasm yasm gettext autoconf automake python@3.9

    - name: Build Deps
      run: |
        mkdir ${{ github.workspace }}/deps
        cd ${{ github.workspace }}/deps
        
        wget https://gist.githubusercontent.com/zumbo666/9b4eb718fa0a082e20516ca985f59d5c/raw/dfed1286f251d57474dac52dab78f03d98948c26/compile_im_deps_intel.sh

        sh compile_im_deps_intel.sh
