name: macOS Test

on:
  push:
    tags:        
      - '**'
  workflow_dispatch:

jobs:
  build-macos:
    name: macOS Build
    runs-on: macos-12

    env:
      BASE_DIR: ${{ github.workspace }}/im_build 
      WORKING_DIR: ${{ github.workspace }}

    steps:
    - name: Install dependencies
      run: |
        set -e
        
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew install brew install pkg-config nasm yasm gettext autoconf automake python@3.9

    - name: Build Deps
      run: |
        mkdir ${{ github.workspace }}/deps
        cd ${{ github.workspace }}/deps
        
        wget https://gist.githubusercontent.com/zumbo666/1ff854cf568bfd4854c3cb99e21e8273/raw/56eae2d5b47a829790e7c323e169fff222146aac/compile_im_deps_intel2.sh

        sh compile_im_deps_intel2.sh

    - name: Download ImageMagick
      run: |
        wget https://imagemagick.org/archive/ImageMagick.tar.gz
        tar -xzvf ImageMagick.tar.gz
        
    - name: Build ImageMagick
      run: |
      	DELEGATES="${{ github.workspace }}/deps/im_build"
      
      	export CC="clang -mmacosx-version-min=10.15"
      	export CXX="clang++ -std=c++17 -stdlib=libc++ -mmacosx-version-min=10.15"
      	export OBJC="clang -mmacosx-version-min=10.15"
      	export OBJCXX="clang++ -std=c++17 -stdlib=libc++ -mmacosx-version-min=10.15"
      	export AS="as -mmacosx-version-min=10.15"
      	export LD="ld -macosx_version_min 10.15"
      
      	export CPPFLAGS="-I$DELEGATES/include"
      	export LDFLAGS="-L$DELEGATES/lib"
      
      	export LD_LIBRARY_PATH=$DELEGATES/lib
      	export PKG_CONFIG_PATH=$DELEGATES/lib/pkgconfig
      	export LDFLAGS="-L$LD_LIBRARY_PATH -R$LD_LIBRARY_PATH"
      
      	export PATH="$PATH:$DELEGATES/bin"
      
        cd ImageMagick
        ./configure --prefix=${{ github.workspace }}/deps/im_build \
                              --with-quantum-depth=16 \
                              --disable-dependency-tracking \
                              --without-perl \
                              --without-x \
                              --disable-static \
                              --disable-installed \
                              --enable-shared \
                              --with-flif=yes \
                              --with-gslib=yes

        make
        make install
