name: macOS Test

on:
  workflow_dispatch:

jobs:
  build-macos:
    name: macOS Build
    runs-on: macos-12

    env:
      BASE_DIR: ${{ github.workspace }}/im_build 
      WORKING_DIR: ${{ github.workspace }}

    steps:
    - name: Install dependencies
      run: |
        set -e
        
        export HOMEBREW_NO_AUTO_UPDATE=1
        brew install pkg-config nasm yasm gettext autoconf automake python@3.9

    - name: Build Deps
      run: |
        mkdir ${{ github.workspace }}/deps
        cd ${{ github.workspace }}/deps
        
        wget https://gist.githubusercontent.com/zumbo666/899e916b256e4830e80fce5a1ddb0b4f/raw/5e6ef1700cdfee047de5b139c3a7010fd786d930/compile_im_deps_intel.sh

        sh compile_im_deps_intel.sh
